# This is a modified copy of astropy's .travis.yml

# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get. (need g++ for iminuit install)
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
            - g++


env:
    global:
        # Set defaults to avoid repeating in most cases.
        - NUMPY_VERSION=1.15
        - ASTROPY_VERSION=3.0
        - SCIPY_VERSION=1.1
        - OPTIONAL_DEPS=true
        - SETUP_CMD='build_ext --inplace'
        - MAIN_CMD='pytest sncosmo --no-downloads'
        - MPLBACKEND="agg"

    matrix:
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info' MAIN_CMD=''
        - PYTHON_VERSION=3.6 SETUP_CMD='egg_info' MAIN_CMD=''
        - PYTHON_VERSION=3.7 SETUP_CMD='egg_info' MAIN_CMD=''

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        - os: osx
          env: PYTHON_VERSION=3.6

        # Try different python versions
        - os: linux
          env: PYTHON_VERSION=3.5
        - os: linux
          env: PYTHON_VERSION=3.7

        # Try astropy 1.0 version and some older dependencies
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10 SCIPY_VERSION=0.17 ASTROPY_VERSION=1.0

        # Try disabling optional dependencies
        - os: linux
          env: PYTHON_VERSION=3.6 OPTIONAL_DEPS=false

        # Do a pycodestyle test
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='egg_info' MAIN_CMD='./checkstyle'

        # coverage test
        - os: linux
          env: PYTHON_VERSION=3.6 MAIN_CMD='pytest sncosmo --cov=sncosmo'

        # Try a doc build
        - os: linux
          env: PYTHON_VERSION=3.6 SETUP_CMD='install' MAIN_CMD='cd docs && make html'

install:
    - source .continuous-integration/travis/setup_environment_$TRAVIS_OS_NAME.sh
    - python setup.py $SETUP_CMD
script:
    - eval $MAIN_CMD

after_success:
    - if [[ $MAIN_CMD == *"--cov"* ]]; then
        coveralls --rcfile='sncosmo/tests/coveragerc';
      fi
